env:
  contexts:
    - name: "app"
      urls:
        - "http://localhost:3000"
      includePaths:
        - "http://localhost:3000.*"
  parameters:
    failOnError: true
    progressToStdout: true

jobs:
  - type: spider
    parameters:
      context: "app"
      url: "http://localhost:3000"
      maxDuration: 5

  - type: passiveScan-wait
    parameters:
      maxDuration: 5

  - type: report
    parameters:
      template: "sarif-json"
      reportDir: "/zap/wrk/"
      reportFile: "results.sarif"
      reportTitle: "ZAP Scan Report"
      reportDescription: "Baseline DAST scan of latam-calculator"
